name: your_snackbar
description: "Snackbar with customizable feature"
version: 1.0.1
homepage: "https://github.com/Forumbit/your_snackbar"
repository: "https://github.com/Forumbit/your_snackbar"

topics:
  - snackbar
  - toast

platforms:
  android:
  ios:
  linux:
  windows:
  macos:
  web:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
